version: '3.7'

services:
  app: &app
    build:
      context: .dockerdev
      dockerfile: Dockerfile
      args:
        RUBY_VERSION: '3.1'
        PG_MAJOR: '12'
        NODE_MAJOR: '14'
        YARN_VERSION: '1.22.22'
        BUNDLER_VERSION: '2.2.3'
    tmpfs:
      - /tmp

  backend: &backend
    <<: *app
    stdin_open: true
    tty: true
    volumes:
      - .:/app
      - rails_cache:/app/tmp/cache
      - bundle:/usr/local/bundle
      - node_modules:/app/node_modules
      # - packs:/app/public/packs
      - .dockerdev/.psqlrc:/root/.psqlrc:ro
    environment:
      - NODE_ENV=${NODE_ENV:-development}
      - RAILS_ENV=${RAILS_ENV:-development}
      - REDIS_URL=redis://redis:6379/
      # - DATABASE_URL=postgres://postgres:postgres@postgres:5432
      - WEBPACKER_DEV_SERVER_HOST=webpacker
      - BOOTSNAP_CACHE_DIR=/usr/local/bundle/_bootsnap
      - HISTFILE=/app/log/.bash_history
      - PSQL_HISTFILE=/app/log/.psql_history
      - EDITOR=vi
      - MALLOC_ARENA_MAX=2
      - WEB_CONCURRENCY=${WEB_CONCURRENCY:-1}
    env_file:
      - .dockerdev/env/web
      - .dockerdev/env/database
    depends_on:
      - postgres
      - redis

  # runner:
  #   <<: *backend
  #   command: /bin/bash
  #   ports:
  #     - '3000:3000'
  #     - '3002:3002'

  web:
    <<: *backend
    command: bin/dev
    # command: bundle exec rails server -b 0.0.0.0
    ports:
      - '3000:3000'

  postgres:
    image: postgres:12
    volumes:
      - .psqlrc:/root/.psqlrc:ro
      - postgres:/var/lib/postgresql/data
      - ./log:/root/log:cached
    environment:
      - PSQL_HISTFILE=/root/log/.psql_history
    env_file:
      - .dockerdev/env/database
    ports:
      - 5432
    healthcheck:
      test: pg_isready -U postgres -h 127.0.0.1
      interval: 5s

  redis:
    image: redis:5.0-alpine
    volumes:
      - redis:/data
    ports:
      - 6379
    healthcheck:
      test: redis-cli ping
      interval: 1s
      timeout: 3s
      retries: 30

volumes:
  postgres:
  redis:
  bundle:
  node_modules:
  rails_cache:
  packs:
  web_bash_history:
